# Generated by Django 6.0.7 on 2026-09-02 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='sla_days',
            field=models.IntegerField(default=7),
        ),
    ]
