# Generated by Django 6.0.7 on 2026-09-03 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0003_complaint_is_overdue_complaint_resolved_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='citizen_confirmed_resolved',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='citizen_feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='citizen_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
