# Generated by Django 6.0.7 on 2026-09-03 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0004_complaint_citizen_confirmed_resolved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='resolved_image',
            field=models.ImageField(blank=True, null=True, upload_to='resolution_evidence/'),
        ),
    ]
