# Generated by Django 6.0.7 on 2026-09-08 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0005_complaint_resolved_image'),
        ('departments', '0003_worker'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='assigned_worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='departments.worker'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='expected_completion_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
